### ISSUE TITLE
How to add multi excludeIndex?

### ISSUE THREAD

**Issue by fimwest** [eirikpre/VSCode-SystemVerilog#192]
I add this setting: 
`"systemverilog.excludeIndexing": "**/*cache/**, **/*gen/**, **/*ip_user_files/**"`,
but it is no use.
If I add this setting:
`"systemverilog.excludeIndexing": "**/*gen/**"`,
it works.
So how to add multi excludeIndex?

**Comment by joecrop** [comment]
I think something like this will get you on the right track:

```js
"systemverilog.excludeIndexing": "**/*{cache,gen,ip_user_files}/**"
```

Note that you should also not have any spaces between names/paths in a glob pattern.

**Comment by fimwest** [comment]
It works. Thank you.
