### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by AndreMerendeira** [eirikpre/VSCode-SystemVerilog#208]
- Issue Type: `Performance`
- Extension Name: `systemverilog`
- Extension Version: `0.13.4`
- OS Version: `Linux x64 6.2.0-37-generic`
- VS Code version: `1.85.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///tmp/eirikpre.systemverilog-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by joecrop** [comment]
@AndreMerendeira can you attach the file please? How many indexed objects does your workspace have?

**Comment by joecrop** [comment]
This is likely due to an extension version issue. High-CPU load was fixed in a recent version. Please update the extension and report a new ticket if this happens again with more information.

**Comment by AndreMerendeira** [comment]
Hi Joe, yes, this was fixed in recent versions, I forgot to close the issue. Thanks!
