### ISSUE TITLE
Color highlighting

### ISSUE THREAD

**Issue by CatWithoutBoots** [eirikpre/VSCode-SystemVerilog#22]
Can you make different **localparam** color and **variable** color?
For example **bold** is "Red" and _italic_ is "Blue".
localparam **my_param**;
logic[31:0] _my_var_;

**Comment by eirikpre** [comment]
Hm, the problem is that the textmate matching cannot follow the variable name, so further on in the code (when var/param is used) there would be no way to apply the same color as in the instantiation.

I'll close issue, but keep it in my mind if it's possible to get this kind of matching
