### ISSUE TITLE
Syntax highlighting in comments

### ISSUE THREAD

**Issue by arquer** [eirikpre/VSCode-SystemVerilog#233]
keywords seem to be highlighted even in comments
![image](https://github.com/user-attachments/assets/dfc38909-5fe5-420e-8054-4d5bb0b85009)

**Comment by joecrop** [comment]
Are you sure this isn't coming from a different extension? I don't see that behavior when I run a clean vscode with only this extension.
![image](https://github.com/user-attachments/assets/e215abb4-1677-4da8-a92c-ecec0cd7aa64)

**Comment by arquer** [comment]
hmm I'll do some more checking

**Comment by Muione** [comment]
I have met the same issue that keywords  is highlighted  in comments, for eaxmple:
![image](https://github.com/user-attachments/assets/4aaffe8b-e20e-4eb2-b600-a190fe2f2941)

**Comment by arquer** [comment]
I have noticed that this often happens when you have just opened a file and the parser is still figuring it out. If you let it work for a bit (and specially if you scroll up and down these tend to go away).

I am closing this.
