### ISSUE TITLE
Incorrect highlighting for variable declarations for types containing the words 'task' and 'function'

### ISSUE THREAD

**Issue by ghraelo** [eirikpre/VSCode-SystemVerilog#36]
```systemverilog
class some_class;
    int an_int;
    some_type the_type;
    type_ending_in_task the_task;
    type_ending_in_function the_function;

endclass
```
This code example displays as:
![image](https://user-images.githubusercontent.com/11276091/51084495-8b01f900-1722-11e9-9cb5-458918254df5.png)

**Comment by eirikpre** [comment]
Ups :)
Good find, I think I know of an easy fix.
Will do a new release sometime this week.
