### ISSUE TITLE
Syntax highlighting can't keep up with Allman indentation style

### ISSUE THREAD

**Issue by gcrabbe** [eirikpre/VSCode-SystemVerilog#41]
The syntax highlighting feature has trouble with indentation styles, such as Allman, where the opening brackets are on a line of their own:

![syntax](https://user-images.githubusercontent.com/28896839/54588654-e5ba1880-4a23-11e9-9268-f996b4cf5bd3.png)

**Comment by eirikpre** [comment]
Yeah, that it a limitation to the current implementation :(
It's part of the backlog to write the textmate matching more iterative, instead of matching per line like now.
The indexing features have been prioritized lately since they caused slowdowns.

**Comment by eirikpre** [comment]
@jecassis You mentioned this issue in the PR as fixes. Does it do that on your end?

From what I can see textmate is only matching one line at a time. If it is going to match multiple lines, only the first word has to be in the "begin" expression.

**Comment by jecassis** [comment]
I have been making additional changes, however it looks right on my side repository. I have a few more corner cases to address and I will submit another set.

<img width="135" alt="Allman Style" src="https://user-images.githubusercontent.com/36133/105274150-72b6e700-5b51-11eb-98b4-698cc2438844.png">

**Comment by eirikpre** [comment]
Should now be working correctly.
Big thanks to the great changes to the textmate setup by @jecassis
