### ISSUE TITLE
Incorrect highlighting for unique case and enumeration.

### ISSUE THREAD

**Issue by Xusine1131** [eirikpre/VSCode-SystemVerilog#42]
The syntax highlighting for unique case with two keywords in the same line is incorrect. It seems to be recognized as a module called unique instantiation:
![](https://i.loli.net/2019/03/23/5c95eb50b365d.png)
And as you can see, my enumeration values which are not capitalized can not be identified and highlighted but the capitalized one (EDONE) can.

**Comment by eirikpre** [comment]
The matching of enumerated values are quite dumb, but lack of time and a good idea made it so.

It is just matching all uppercase words, and uses the same color as numbers.
Often uppercase words are either parameters or enumerated types.

**Comment by Xusine1131** [comment]
Why not maintain a symbol list for enumerated value?

**Comment by eirikpre** [comment]
The biggest problem is mainly that textmate (syntax coloring) is totally separate from the typescript scripts that parses the 'intelligently'.

Textmate afaik at least, doesn't have an easy way to store symbols encountered earlier in a file.
