### ISSUE TITLE
Code section collapse

### ISSUE THREAD

**Issue by CatWithoutBoots** [eirikpre/VSCode-SystemVerilog#50]
Can you organize code section collapse of SystemVerilog source code in IDE VisualStudioCode?
For example
//#region DSP processing
assign snk_ready = src_ready & ~src_valid;
always_ff @(posedge clk)
  // Some code...
//#endregion DSP processing

**Comment by CatWithoutBoots** [comment]
https://stackoverflow.com/questions/30067767/how-do-i-collapse-sections-of-code-in-visual-studio-code-for-windows

**Comment by eirikpre** [comment]
Hm yes, can do that.
I was not easily able to do overlapping regions, because it can only look for #region / #endregion.
Nested regions seem to work fine
