### ISSUE TITLE
As of release 6.0. bracket matching for case statements don't seem to be working

### ISSUE THREAD

**Issue by bman844** [eirikpre/VSCode-SystemVerilog#53]
On release 5.6, it appears that it matches correctly. Every version after that doesn't seem to do that as far as I can tell. 

Here it is in 5.6 
![image](https://user-images.githubusercontent.com/8868581/60619159-a7135880-9d9d-11e9-8bcb-e19c812e7100.png)
Here it is in 6.0
![image](https://user-images.githubusercontent.com/8868581/60619210-bd211900-9d9d-11e9-853b-52e43db72e63.png)

**Comment by eirikpre** [comment]
Hm, that's strange, it's not showing like that on my end.
Perhaps you can see what you get out of:
![image](https://user-images.githubusercontent.com/10548539/60663994-11410180-9e61-11e9-9c3e-af71d6396e56.png)

If it's just my extension working on the document, hopefully it only matches with: _keyword.control.selection.systemverilog_ and _text.systemverilog_

**Comment by bman844** [comment]
I did as you suggested, and noted that both keywords are identified with keyword.control.selection.systemverilog and text.systemverilog

Looking at the behavior without any other extensions installed in the most recent version, I noted an area it behaves strangely. 


![image](https://user-images.githubusercontent.com/8868581/61325371-2e1ef280-a7da-11e9-938e-82f8954e1111.png) 

![image](https://user-images.githubusercontent.com/8868581/61325386-37a85a80-a7da-11e9-9520-3c9cb392b924.png)

In the first image, the brackets appear to match when the cursor is on the the case keyword, while they no longer appear to match when the cursor is on the endcase keyword. Using the Ctrl+Shift+\ shortcut to jump to the matching bracket seems to show a similar story. The jump will jump for "case" to "endcase", but will not work for jumping from "endcase" to "case." This behavior does work fine with "begin"s and "end"s, but does not seem to handle "case"s and "endcase"s too well. I don't know if this is something you can replicate on your end.

**Comment by bman844** [comment]
I decided to take the time to look through commits and see what the differences were. I think I found the potential issue and I imagine the fix might not be too bad, but I have no idea how to go about it since I have no experience personally with VS Code extensions. 

At a couple of points between version 5.6, and version 6.0, there were a couple of commits regarding adding support for randcase. in the language-configuartion. What I have noted is in the brackerts section of the language-configuration.json, there are two bracket types that end with endcase. You can see them here. Both case and randcase have keywords ending with endcase. I think that may be the reason as to why it may be able to jump forward, but not necessarily backwards. 

![image](https://user-images.githubusercontent.com/8868581/61327998-bf449800-a7df-11e9-8760-c077d0f1a67e.png)

**Comment by eirikpre** [comment]
Good find! Thanks for finding the source, I will see if it can match both case and randcase properly or change back to only case matching. Seems like what you found is me misusing the language config.
Will see to it next week after vacation :)

**Comment by bman844** [comment]
Glad to have helped! : )
