### ISSUE TITLE
Feature request: Index macros

### ISSUE THREAD

**Issue by Jibbajabbafic** [eirikpre/VSCode-SystemVerilog#61]
It would be nice if macros were indexed too so they work with 'Go to Definition'

**Comment by eirikpre** [comment]
Added, it but it will not be parsed in large workspaces because i could not mix it with the fast regex (being used for big workspaces)
More info on that here: 
https://github.com/eirikpre/VSCode-SystemVerilog/issues/29#issuecomment-519964904

Will be included in the next marketplace release

**Comment by Jibbajabbafic** [comment]
Awesome, thanks for the speedy addition!
