### ISSUE TITLE
A bug about code folding of macro definition

### ISSUE THREAD

**Issue by bitrocco** [eirikpre/VSCode-SystemVerilog#65]
I found this bug when the code contained a lot of precompiled macros. If only **\`ifdef**, **\`endif** is included, the code folding is correct. As shown below : 

![folding 1](https://user-images.githubusercontent.com/30104601/66178585-6c6cd500-e698-11e9-97a3-934615400e48.png)

When **\`elsif**, **\`else** appears, only the last code block will be folded. As shown below : 

![folding 2](https://user-images.githubusercontent.com/30104601/66178675-c1a8e680-e698-11e9-8b3d-50f7978e7c9e.png)

I found the code that controls the code folding in _language-configuration.json_ as shown below, but it doesn't seem to work, so I proposed this issue. Is there any way to solve it?

```json
{
    "folding": {
        "offSide": false,
        "markers": {
            "start": "^\\s*`(ifdef|ifndef|elsif|else)|(\/\/#region)",
            "end": "^\\s*`(elsif|else|endif)|(\/\/#endregion)"
        },
    }
}
```

**Comment by eirikpre** [comment]
Heya, sorry for a late response.

Yeah I noticed the same, but had no immediate ideas.

I think it's not willing to match the same line twice, I tried a few changes but no solution.

I think the only solution is to implement one of these [FoldingRangeProvider](https://code.visualstudio.com/api/references/vscode-api#FoldingRangeProvider), which requires a bit more time.

Keeping the task open, but this has little priority. I suggest using indentation when using those, and it will grasp folding markers from that.
