### ISSUE TITLE
Add array support for Exclude Indexing setting

### ISSUE THREAD

**Issue by Jibbajabbafic** [eirikpre/VSCode-SystemVerilog#78]
It's not clear right now if multiple exclude indexing globs are supported so it would be nice to implement the setting as an array like the default File Exclude VSCode setting.

Example:
![image](https://user-images.githubusercontent.com/4493127/73952590-0c609680-48f7-11ea-9aa4-d0acbbdfcda0.png)

How it appears in the settings:
```
		"files.exclude": {
			"**/.git": true,
			"**/.svn": true,
			"**/.hg": true,
			"**/CVS": true,
			"**/.DS_Store": true
		}
```

**Comment by eirikpre** [comment]
I think it is supported through glob with {<a>,<b>}.

I can make the setting an array and concat, but low prio at the moment

**Comment by Jibbajabbafic** [comment]
Alright thanks, I'll try that method

**Comment by eirikpre** [comment]
Doing a bit of spring cleaning, if the fix mentioned did not work, reopen the issue
