### ISSUE TITLE
Feature Request: Find Usages

### ISSUE THREAD

**Issue by AlexLao512** [eirikpre/VSCode-SystemVerilog#90]
Excellent plugin, I am moving from SublimeText with this plugin https://packagecontrol.io/packages/SystemVerilog

You have some nice features and the SublimeText plugin has other nice ones. The feature I think I am missing the most when trying yours out is the ability to hover over a module definition and jump to all usages/references.

**Comment by schegde** [comment]
Yesssss!! This is the only important feature that I find missing in this otherwise strong VS code extension. The Find references/usage would be very handy to quickly find all instantiations of a (possibly heavily-reused) IP, and that makes it easy for navigating large codebases.
