### ISSUE TITLE
UVM extension

### ISSUE THREAD

**Issue by RomanLeonB** [eirikpre/VSCode-SystemVerilog#97]
Hi,
thanks for the great extension :).
Do you have plans about an UVM extension (maybe for the 20 important classes)?

Roman

**Comment by eirikpre** [comment]
Heia!
Not planned for this extension. There is this extension catered towards UVM: [SystemVerilog-1800-2012](https://marketplace.visualstudio.com/items?itemName=gvekony.systemverilog-1800-2012 )
You can use the setting includeIndexing to include the uvm files which might work for you. (Most people do not have uvm in their workspace), previous comment https://github.com/eirikpre/VSCode-SystemVerilog/issues/67#issuecomment-624608387

**Comment by RomanLeonB** [comment]
> Heia!
> Not planned for this extension. There is this extension catered towards UVM: [SystemVerilog-1800-2012](https://marketplace.visualstudio.com/items?itemName=gvekony.systemverilog-1800-2012 )
> You can use the setting includeIndexing to include the uvm files which might work for you. (Most people do not have uvm in their workspace), previous comment https://github.com/eirikpre/VSCode-SystemVerilog/issues/67#issuecomment-624608387

Ok thanks, is it possible to support the repository?

**Comment by eirikpre** [comment]
Not sure what you mean by support the repository? :)
